M48
; DRILL file {KiCad 9.0.1} date 2025-05-21T18:25:46+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-21T18:25:46+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.130
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X120.16Y-44.35
T2
X109.2Y-97.02
X121.3Y-97.02
M30
